app/categories/__init__.py
from flask import Blueprint

category_blueprint= Blueprint('categories', __name__, url_prefix='/categories')
from app.categories import views

app/categories/views.py
from flask import  request,render_template, redirect, url_for
from app.models import db
from app.models import Category
from app.categories import category_blueprint


@category_blueprint.route('hello')
def helloworld():
  return "<h1>Hello World Caaaat!</h1>"

@category_blueprint.route('', endpoint='index')
def index():
  categories = Category.get_all_objects()
  return render_template('categories/index.html', categories=categories)

# Create category
@category_blueprint.route('/create', endpoint='create', methods=['GET', 'POST'] )
def create():
  categories = Category.get_all_objects()
  if request.method == 'POST':
    print('Received Data', request.form)
    category = Category(name=request.form['name'])
    category.save_category()
    return redirect(url_for('categories.index'))
  return render_template('categories/create.html', categories=categories)

# Get category
@category_blueprint.route('<int:id>', endpoint='show', methods=['GET'])
def get_category(id):
  category = Category.query.get_or_404(id)
  if category:
    return render_template('categories/show.html', category=category)
  else:
    return 404
  
# Delete category
@category_blueprint.route('<int:id>/delete', endpoint='delete', methods=['GET'])
def delete_category(id):
  category = Category.query.get_or_404(id)
  if category:
    db.session.delete(category)
    db.session.commit()
    return redirect(url_for('categories.index'))
  else:
    return 404

# Edit category
@category_blueprint.route('<int:id>/edit', endpoint='edit', methods=['GET', 'POST'])
def edit_category(id):
  category = Category.query.get_or_404(id)
  if request.method == 'POST':
    category.name = request.form['name']
    db.session.commit()
    return redirect(category.get_show_url)
  return render_template('categories/edit.html', category=category)

app/templates/categories/create.html
{% extends 'layouts/base.html' %}
{% block title %} Create Category {% endblock %}
{% block body %}
<form method="post" enctype=multipart/form-data>
  <div class="mb-3">
    <label for="" class="form-label">Name</label>
    <input type="text"  name='name' class="form-control" id="" aria-describedby="emailHelp">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

app/templates/categories/edit.html
{% extends 'layouts/base.html' %}
{% block title %} Edit Category {% endblock %}
{% block body %}
<form method="post" enctype=multipart/form-data>
  <div class="mb-3">
    <label for="" class="form-label">Name</label>
    <input type="text"  name='name' value="{{category.name}}" class="form-control" id="" aria-describedby="emailHelp">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

app/templates/categories/index.html
{% extends 'layouts/base.html' %}
{% block title %} Categories {% endblock %}
{% block body %}
  <div>
    <a href="{{url_for('categories.create')}}" class="text-success fs-4"><i class="fa-solid fa-square-plus"></i></a>
  </div>
  <table class="table my-5" id="dataTable" width="100%" cellspacing="0">
    <tr class="bg-success text-white"> 
      <th class="py-3">ID</th>  
      <th class="py-3">Name</th>
      <th class="py-3">Show</th>
      <th class="py-3">Edit</th>
      <th class="py-3">Delete</th>
    </tr>

    {% for category in categories %}
      <tr>
        <td>{{category.id}}</td>
        <td>{{category.name}}</td>
        <td>
          <a href="{{category.get_show_url}}" class="btn text-success ">
            <i class="fa-regular fa-eye"></i>
          </a>
        </td>
        <td>
          <a href="{{url_for('categories.edit', id=category.id)}}" class="btn text-success ">
            <i class="fa-regular fa-pen-to-square"></i>
          </a>
        </td>
        <td>
          <a href="{{category.get_delete_url}}" class="btn text-danger">
            <i class="fa-solid fa-minus"></i>
          </a>
        </td>
            
      </tr>
    {% endfor %}
  </table>
{% endblock %}

app/templates/categories/show.html
{% extends 'layouts/base.html' %}
{% import 'macros/macros.html' as myposts %}
{% block title %} {{category.name}} {% endblock %}
{% block body %}
  <div class="container py-5">
    <h1 class="mb-4">{{category.name}}</h1>
    <div class="row">
      {% for post in category.posts %}
      <div class="col-sm-6 mb-3 mb-sm-0 d-flex justify-content-center ">
        <div class="card mb-3 border-0 rounded rounded-0 " style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{post.get_image_url}}" class="img-fluid" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body py-0">
                <p class="card-title fw-semibold ">{{post.title}}</p>
                <p class="card-text">{{post.body}}</p>
                <p class="card-text"><small class="text-body-secondary">Last updated {{post.updated_at}}</small></p>
                <div class="links">
                <a href="{{post.get_show_url}}" class="btn text-success "><i class="fa-regular fa-eye"></i></a>
                <a href="{{url_for('posts.edit', id=post.id)}}" class="btn text-success "><i class="fa-regular fa-pen-to-square"></i></a>
                <a href="{{post.get_delete_url}}" class="btn text-danger "><i class="fa-solid fa-minus"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}