app/posts/__init__.py
from flask import Blueprint

post_blueprint= Blueprint('posts', __name__, url_prefix='/posts')
from app.posts import views

app/posts/views.py
from flask import  request,render_template, redirect, url_for
from app.models import db
from app.models import Post
from app.models import Category
from app.posts import post_blueprint
from werkzeug.utils import secure_filename
import os

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
  return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@post_blueprint.route('hello')
def helloworld():
  return "<h1>Hello World!</h1>"

@post_blueprint.route('', endpoint='index')
def index():
  posts = Post.get_all_objects()
  return render_template('posts/index.html', posts=posts)

# Create Post
@post_blueprint.route('/create', endpoint='create', methods=['GET', 'POST'] )
def create():
  categories = Category.get_all_objects()
  if request.method == 'POST':
    print('Received Data', request.form)
    if 'image' in request.files:
      file = request.files['image']
      if file.filename != '':
        if file and allowed_file(file.filename):
          filename = secure_filename(file.filename)
          current_directory = os.path.dirname(__file__)
          destination = os.path.abspath(os.path.join(current_directory, "../../app/static/posts/images"))
          destination_path = os.path.join(destination, filename)
          print('DES:' , destination_path)
          file.save(destination_path)
      else:
        filename = None
    
    post = Post(title=request.form['title'], body=request.form['body'], image=filename, category_id=request.form['category_id'])
    post.save_post()
    return redirect(url_for('posts.index'))
  return render_template('posts/create.html', categories=categories)

# Get Post
@post_blueprint.route('/posts/<int:id>', endpoint='show', methods=['GET'])
def get_post(id):
  post = Post.query.get_or_404(id)
  if post:
    return render_template('posts/show.html', post=post)
  else:
    return 404
  
# Delete Post
@post_blueprint.route('/posts/<int:id>/delete', endpoint='delete', methods=['GET'])
def delete_post(id):
  post = Post.query.get_or_404(id)
  if post:
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('posts.index'))
  else:
    return 404

# Edit Post
@post_blueprint.route('/posts/<int:id>/edit', endpoint='edit', methods=['GET', 'POST'])
def edit_post(id):
  post = Post.query.get_or_404(id)
  categories = Category.get_all_objects()
  if request.method == 'POST':
    print('Received Data', request.form)
    post.title = request.form['title']
    post.body = request.form['body']
    post.category_id = request.form['category_id']
    file = request.files['image']
    if file.filename != '':
      if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        current_directory = os.path.dirname(__file__)
        destination = os.path.abspath(os.path.join(current_directory, "../../app/static/posts/images"))
        destination_path = os.path.join(destination, filename)
        print('DES:' , destination_path)
        file.save(destination_path)
        post.image = filename
    else:
      filename = None
    
    db.session.commit()
    return redirect(post.get_show_url)
  return render_template('posts/edit.html', post=post, categories=categories)

app/templates/posts/create.html
{% extends 'layouts/base.html' %}
{% block title %} Create Post {% endblock %}
{% block body %}
<form method="post" enctype=multipart/form-data>
  <div class="mb-3">
    <label for="" class="form-label">Title</label>
    <input type="text"  name='title' class="form-control" id="" aria-describedby="emailHelp">
  </div>
    <div class="mb-3">
    <label for="" class="form-label">Body</label>
    <textarea name='body' class="form-control" aria-describedby="emailHelp"></textarea>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Image</label>
    <input type="file" name='image' class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <select class="form-select" name="category_id" aria-label="Default select example">
      <option selected disabled value="">Open this select menu</option>
      {% for category in categories %}
      <option value='{{category.id}}'>{{category.name}}</option>
      {% endfor %}
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

app/templates/posts/edit.html
{% extends 'layouts/base.html' %}
{% block title %} Edit Post {% endblock %}
{% block body %}
<form method="post" enctype=multipart/form-data>
  <div class="mb-3">
    <label for="" class="form-label">Title</label>
    <input type="text"  name='title' value="{{post.title}}" class="form-control" id="" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Body</label>
    <textarea name='body' value="" class="form-control" aria-describedby="emailHelp">{{post.body}}</textarea>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Image</label>
    <input type="file" name='image' value="{{post.image}}" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <select class="form-select" name="category_id" aria-label="Default select example">
      <option selected disabled value="">Open this select menu</option>
      {% for category in categories %}
      {% if post.category_id == category.id %} 
        <option value='{{category.id}}' selected>{{category.name}}</option>
      {% else %}
        <option value='{{category.id}}'>{{category.name}}</option>
      {% endif %}
      {% endfor %}
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

app/templates/posts/index.html
{% extends 'layouts/base.html' %}
{% block title %} Posts {% endblock %}
{% block body %}
  <div class="mb-3 ms-5">
    <a href="{{url_for('posts.create')}}" class="text-success fs-4"><i class="fa-solid fa-square-plus"></i></a>
  </div>
  <div class="row">
    {% for post in posts %}
    <div class="col-sm-6 mb-3 mb-sm-0 d-flex justify-content-center ">
      <div class="card mb-3 border-0 rounded rounded-0 " style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{post.get_image_url}}" class="img-fluid" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body py-0">
              <p class="card-title fw-semibold ">{{post.title}}</p>
              <p class="card-text">{{post.body}}</p>
              <p class="card-text"><small class="text-body-secondary">Last updated {{post.updated_at}}</small></p>
              <div class="links">
              <a href="{{post.get_show_url}}" class="btn text-success "><i class="fa-regular fa-eye"></i></a>
              <a href="{{url_for('posts.edit', id=post.id)}}" class="btn text-success "><i class="fa-regular fa-pen-to-square"></i></a>
              <a href="{{post.get_delete_url}}" class="btn text-danger "><i class="fa-solid fa-minus"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

app/templates/posts/show.html
{% extends 'layouts/base.html' %}
{% import 'macros/macros.html' as myposts %}
{% block title %} {{post.title}} {% endblock %}
{% block body %}
  <div class="row p-5 shadow-sm border-2 mx-auto " style="background-color: #eee; width: 1000px;">
    <div class="col">
      <img src="{{post.get_image_url}}" alt="">
    </div>
    <div class="col">
      <h5 class="card-title">{{post.title}}</h5>
      <hr>

      <p class="card-text">{{post.body}}</p>
      <hr>

      <p class="card-text"><small class="text-body-secondary">Category:  {{post.category_name}}</small></p>
      <hr>

      <p class="card-text"><small class="text-body-secondary">Created:  {{post.created_at}}</small></p>
      <p class="card-text"><small class="text-body-secondary">Last updated: {{post.updated_at}}</small></p>
      <hr>

      <div class="links">
        <a href="{{url_for('posts.edit', id=post.id)}}" class="btn text-success "><i class="fa-regular fa-pen-to-square"></i></a>
        <a href="{{post.get_delete_url}}" class="btn text-danger "><i class="fa-solid fa-minus"></i></a>
      </div>
      <hr>

      <div>
        <a href="{{url_for('posts.index')}}" class="btn btn-outline-success">&larr; Back To Posts Home</a>
      </div>
    </div>
  </div>
{% endblock %}